# Generated by Django 3.2.9 on 2022-01-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stata_control_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=50, upload_to='stata_files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
    ]
