# Generated by Django 3.2.9 on 2022-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stata_control_panel', '0002_auto_20220105_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagData',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
    ]
