# Generated by Django 3.2.9 on 2022-01-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stata_control_panel', '0003_tagdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseData',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('columns', models.CharField(max_length=1000)),
            ],
        ),
    ]
