# Generated by Django 3.2.9 on 2022-01-19 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stata_control_panel', '0004_databasedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseData',
        ),
        migrations.AddField(
            model_name='database',
            name='columns',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
