# Generated by Django 3.2.9 on 2022-01-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stata_control_panel', '0005_auto_20220119_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='name',
        ),
    ]
